Repository 2206-fsa-best-team/VibeCheck, pull requests merged in 2022-09, with the labels that each got.

#173 Auth redirection
  src/App.js
  src/Components/Journals/SingleJournal.js
  src/Components/Moments/SingleMoment.js
Labels: enhancement

#180 Update README.md
  README.md
Labels: documentation

#179 beginning of aria labeling
  package.json
  server/ocr.js
  src/Components/Buttons/LightDarkButton.js
  src/Components/Camera.js
  src/Components/Journals/AddJournal.js
  src/Components/Journals/CheckConf.js
  src/Components/Navigation/Navbar.js
Labels: enhancement

#182 Single Moment Styling+
  src/Components/Buttons/FloatingDeleteMobile.js
  src/Components/Buttons/FloatingDeleteWeb.js
  src/Components/Buttons/FloatingEditMobile.js
  src/Components/Buttons/FloatingEditWeb.js
  src/Components/Journals/AddJournal.js
  src/Components/Journals/JournalEntryDetails.js
  src/Components/Journals/Journals.js
  src/Components/Journals/SingleJournal.js
  src/Components/Moments/AddMoment.js
  src/Components/Moments/MomentCard.js
  src/Components/Moments/MomentDetails.js
  src/Components/Moments/Moments.js
  src/Components/Moments/SingleMoment.js
Labels: enhancement

#190 Button fix
  src/Components/Camera.js
Labels: enhancement

#191 updated settings format
  src/Components/Settings/SettingsScreen.js
Labels: enhancement

#192 Leftside Add Buttons
  src/Components/Buttons/AddJournalEntryButton.js
  src/Components/Buttons/AddMomentButton.js
  src/Components/Buttons/FloatingAdd.js
  src/Components/Journals/Journals.js
  src/Components/Moments/Moments.js
  src/Components/Navigation/SideMenu.js
Labels: enhancement

#193 Camera fix
  imgFiles/test.webp
  src/Components/Camera.js
Labels: bug

#194 Avatar color
  src/Components/Buttons/AddMomentButton.js
  src/Components/Navigation/Footer.js
  src/Components/Navigation/Navbar.js
  src/Components/Navigation/SideMenu.js
Labels: enhancement

#197 camera changes
  src/Components/Journals/AddJournal.js
Labels: enhancement

#200 Text spacing
  imgFiles/test.webp
  src/Components/Camera.js
  src/Components/Journals/CheckConf.js
Labels: enhancement

#204 snap another pic
  imgFiles/test.webp
  src/Components/Camera.js
  src/Components/Journals/AddJournal.js
  src/Components/Journals/CheckConf.js
Labels: enhancement

#205 Fixed issue of sidebar covering content
  src/Components/Navigation/SidePhoto.js
Labels: bug

#206 Theme & Default Colors
  src/Components/About/AboutSingle.js
  src/Components/Buttons/AddJournalEntryButton.js
  src/Components/Buttons/AddMomentButton.js
  src/Components/Buttons/FloatingAdd.js
  src/Components/Buttons/FloatingDeleteMobile.js
  src/Components/Buttons/FloatingDeleteWeb.js
  src/Components/Buttons/FloatingEditMobile.js
  src/Components/Buttons/FloatingEditWeb.js
  src/Components/Buttons/Slider.js
  src/Components/Camera.js
  src/Components/Charts/VibesLineGraph.js
  src/Components/ErrorPages/ErrorPage.js
  src/Components/ErrorPages/Offline.js
  src/Components/Helpers/colorChanger.js
  src/Components/Helpers/vibeMsgSelector.js
  src/Components/Journals/AddJournal.js
  src/Components/Journals/CheckConf.js
  src/Components/Journals/JournalEntryCard.js
  src/Components/Journals/JournalEntryDetails.js
  src/Components/Login/Auth.js
  src/Components/Login/WelcomeProfile.js
  src/Components/Moments/AddMoment.js
  src/Components/Moments/MomentCard.js
  src/Components/Moments/MomentDetails.js
  src/Components/Moments/Moments.js
  src/Components/Navigation/Footer.js
  src/Components/Navigation/Navbar.js
  src/Components/Navigation/SideMenu.js
  src/Components/Settings/SettingsScreen.js
  src/index.js
  src/theme/theme.js
Labels: enhancement

#207 Updated side banners and made them switchable with light and dark modes
  src/Components/Navigation/SidePhoto.js
Labels: enhancement

#208 adds vibe coloring to single moment/entry views
  src/Components/Journals/JournalEntryDetails.js
  src/Components/Moments/MomentDetails.js
Labels: enhancement

#209 make AddJournal camera a bit sleeker
  src/Components/Buttons/Slider.js
  src/Components/Camera.js
  src/Components/Journals/AddJournal.js
  src/Components/Moments/AddMoment.js
Labels: enhancement

#210 updates logo to clickable svg
  public/index.html
  src/Components/Navigation/Navbar.js
  src/Components/Navigation/SideMenu.js
  src/Components/Navigation/logo.js
Labels: enhancement

#211 first draft nlp sentiment analysis working
  package.json
  server/index.js
  src/Components/Journals/AddJournal.js
  src/Components/Journals/CheckConf.js
Labels: enhancement

#216 API key now stored on Heroku
  src/server/supabaseClient.js
Labels: urgent

#214 fixes tooltip coloring removed by theme implementation
  src/Components/Charts/VibesLineGraph.js
Labels: bug

#215 Moblie styling
  public/check_192.png
  public/check_512.png
  public/favicon.ico
  public/index.html
  public/maskable_icon_192 .png
  public/maskable_icon_192.png
  src/Components/Charts/VibeCharts.js
  src/Components/Journals/Journals.js
Labels: bug, enhancement
